version: '3'
volumes:
  dados:
networks: 
  banco:
  web:
  fila:
services:
  db:
    image: postgres:11.8-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - web
      - banco
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=email_sender
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - REDIS_HOST=queue
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app